### ISSUE TITLE
scan 返回的列表转换为 []map[string]interface{}

### ISSUE THREAD

**Issue by Gxiaodiao** [mei-rune/GoBatis#10]
你好，查询列表返回值，是一个动态，想转换为 []map[string]interface{}，能否支持下

**Comment by Gxiaodiao** [comment]
还发现标签的问题：
mybatis是<choose> gobatis是<chose> 这个是特意这样写的吗

**Comment by mei-rune** [comment]
我改了 ，  choose 和 chose 都支持了。
当初拼写错误， 后来发现也没有改

**Comment by Gxiaodiao** [comment]
> 我改了 ， choose 和 chose 都支持了。 当初拼写错误， 后来发现也没有改

nice

**Comment by Gxiaodiao** [comment]
> 你好，查询列表返回值，是一个动态，想转换为 []map[string]interface{}，能否支持下

这个能否 直接返回rows，然后我这边灵活去转换

**Comment by mei-rune** [comment]
这个背离我的初衷，但你可以这么做, 用这几个方法

	QueryRow(ctx context.Context, sqlstr string, params []interface{}) SingleRowResult
	Query(ctx context.Context, sqlstr string, params []interface{}) *MultRowResult
	Delete(ctx context.Context, id string, params ...interface{}) (int64, error)
	Update(ctx context.Context, id string, params ...interface{}) (int64, error)
	Insert(ctx context.Context, id string, params ...interface{}) (int64, error)
	SelectOne(ctx context.Context, id string, params ...interface{}) SingleRowResult
	Select(ctx context.Context, id string, params ...interface{}) *MultRowResult
	
	
注决 SingleRowResult 和 MultRowResult 并没有开始执行 SQL ( 它是在 Scan 中才开始执行的)，  它们有一个 SQL() 方法， 你可以用它得到 sql 和  args ， 然后自已执行它。

**Comment by mei-rune** [comment]
你有更好的注意，可以提 pull request 或 想法

**Comment by mei-rune** [comment]
另外  SingleRowResult 有一个 RowScan() 方法
 MultRowResult 可以这么做
 
 var r *MultRowResult  = ......
 for r.Next() {
    rows =  r.Rows() // 得到 sql.Rows
 }
