### ISSUE TITLE
isZero 判断是否为0

### ISSUE THREAD

**Issue by Gxiaodiao** [mei-rune/GoBatis#12]
isZero这个函数，参数类型是int，传进判断的时候，参数类型变为了float32，导致判断失效了
isNoZero 这个函数代码貌似没有提交

**Comment by mei-rune** [comment]
这个 github.com/Knetic/govaluate  的 bug, 有时间我改用  github.com/google/cel-go

你现在可以用  xx == 0 ， 这个不会出错

**Comment by mei-rune** [comment]
isNoZero  是写错了， 正确的是 isNotZero

**Comment by mei-rune** [comment]
现在 isZero(1) 好了， 我将 github.com/Knetic/govaluate  改成了 github.com/PaesslerAG/gval

 github.com/google/cel-go 和  github.com/expr-lang/expr 都不能满足要求
