### ISSUE TITLE
参数传值是bol，但是xml解析提示 result of test expression is nil - OperatorBusinessProfit

### ISSUE THREAD

**Issue by Gxiaodiao** [mei-rune/GoBatis#14]
<img width="1491" alt="image" src="https://github.com/mei-rune/GoBatis/assets/10322122/331975c9-e281-46ca-8492-9d70ef8cefd0">

xml是这样写的
<img width="967" alt="image" src="https://github.com/mei-rune/GoBatis/assets/10322122/7c5d2160-20d3-4be6-ab6d-c9a9ebe1b674">
麻烦指点下，是怎么回事

**Comment by Gxiaodiao** [comment]
还有个问题， err:"value isnot slice, array, string or map"
能不能提示下 是哪个参数

**Comment by Gxiaodiao** [comment]
```
 <include refid="operatorBusinessStatisticsQuerySql">
        <!-- 时间赋值 -->
        <property name="DefineStartTime" value="#{FromTime}"/>
        <property name="DefineEndTime" value="#{ToTime}"/>
```
在赋值的时候，提示param 'DefineStartTime' is missing

**Comment by mei-rune** [comment]
这个和你定义的方法有关

> ```
>  <if test=" TimeType == nil ">
>             test
>         </if>
> ```
> 
> 我的结构体里面，定义的
> 
> ```
> type Result struct {
>  TimeType  *int 
> }
> ```
> 
> 判断的是时候，如果TimeType不能入 if里面，如果我传值了，结果进去了，是不是判断写反了

这个 是 github.com/PaesslerAG/gval 的问题， 我刚改好了，晚点提交

**Comment by mei-rune** [comment]
> > <img alt="image" width="1491" src="https://private-user-images.githubusercontent.com/10322122/333987605-331975c9-e281-46ca-8492-9d70ef8cefd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTMxNzcsIm5iZiI6MTcxNjgxMjg3NywicGF0aCI6Ii8xMDMyMjEyMi8zMzM5ODc2MDUtMzMxOTc1YzktZTI4MS00NmNhLTg0OTItOWQ3MGVmOGNlZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMDIzNDgyZTMwYzY5YWRmYzJkYjJiNzIxMDNjYjliMTdlOGRkMzBmYzc5NjM1YjVmZGI2N2I1NmY1NjQ1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LCwlQAjYYGO-u7XRdL2UKh_FxGT3bH972aUHWOmp5cs">
> > xml是这样写的 <img alt="image" width="967" src="https://private-user-images.githubusercontent.com/10322122/333987866-7c5d2160-20d3-4be6-ab6d-c9a9ebe1b674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTMxNzcsIm5iZiI6MTcxNjgxMjg3NywicGF0aCI6Ii8xMDMyMjEyMi8zMzM5ODc4NjYtN2M1ZDIxNjAtMjBkMy00YmU2LWFiNmQtYzlhOWViZTFiNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEyMjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZDdjYTExNDAxMDE1MDRkZGUzZjc3Y2U0YjZhZTAxMDVlODM1MzZjYWI1NTY3MzYzOGQyYWNjN2I0MGIyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vcCINvkZTQiMLViwflbK5sRQt1WZGvN6rxB1ArVpGzw"> 麻烦指点下，是怎么回事
> 
> 这个我没有重现出来， 你的函数是怎么定义的

代码已提交， 但是其它都已解决， 只有这个没有重现， 你可以试试写一个单元测试发给我

**Comment by Gxiaodiao** [comment]
今天发现个问题，查询的字段，作为参数传进去，结果出现错误。比如：查询字段，我传入 tenant_id,area，
sql：
```
id:"user.query", sql:"
        select ? from dim_dept_info_neo where depart_name='总部'
    ", params:"[]interface {}{"tenant_id,area"}", err: null
```
但是返回结果的时候 tenant_id,area 这个两个字段作为了一个参数，麻烦看下

**Comment by mei-rune** [comment]
xml 怎么定义的呢

**Comment by mei-rune** [comment]
另外 字段名不可以作为参数的， sql 不支持的， 在 mybatis 中是用 ${} 这个字符替换， 我是用  \<print  />, 你可以看一下 readme 的说明

**Comment by Gxiaodiao** [comment]
```
<select id="user.query">
        select #{param} from dim_dept_info_neo where depart_name='总部'
    </select>
```
这样定义

**Comment by mei-rune** [comment]
你这个肯定不行，不管在哪里都不行，  字段名是不可以以参数形式提供的， 在 mybatis 中你要写成  

<select id="user.query">
        select ${param} from dim_dept_info_neo where depart_name='总部'
    </select>
    
在这个库中， 你要写成 

<select id="user.query">
        select  <print value="param" /> from dim_dept_info_neo where depart_name='总部'
    </select>

**Comment by Gxiaodiao** [comment]
> <print value="param" />

好的 我试试

**Comment by Gxiaodiao** [comment]
```
id:"user.query", sql:"
        select  <print value="param" /> from dim_dept_info_neo where depart_name='总部'
    ", params:"[]interface {}{"tenant_id,area"}", err:"print value is invalid"
提示这个
```

**Comment by mei-rune** [comment]
我有安全检测， 字符中有特殊字符会报错， 上面这个你还要改一下， 参数以数组形式提供， 然后在  foreach 中嵌套 print

**Comment by Gxiaodiao** [comment]
> 我有安全检测， 字符中有特殊字符会报错， 上面这个你还要改一下， 参数以数组形式提供， 然后在 foreach 中嵌套 print

好的，我试试
# 还有个问题，上次提到的，返回动态列，就是返回一个[]map[string]interface{},value的值 我需要判断下类型，让我做处理，现在我发现使用的你的接口，Select(ctx context.Context, id string, paramNames []string, paramValues []interface{}) *MultRowResult，
在返回 MultRowResult，然后 MultRowResult.next()才去执行查询，是否可以提供，我直接能获取到rows，

**Comment by Gxiaodiao** [comment]
分页，是否能支持下？

**Comment by mei-rune** [comment]
> > 我有安全检测， 字符中有特殊字符会报错， 上面这个你还要改一下， 参数以数组形式提供， 然后在 foreach 中嵌套 print
> 
> 好的，我试试
> # 还有个问题，上次提到的，返回动态列，就是返回一个[]map[string]interface{},value的值 我需要判断下类型，让我做处理，现在我发现使用的你的接口，Select(ctx context.Context, id string, paramNames []string, paramValues []interface{}) *MultRowResult，
> 
> 在返回 MultRowResult，然后 MultRowResult.next()才去执行查询，是否可以提供，我直接能获取到rows，

本来就提供啊

**Comment by mei-rune** [comment]
> 分页，是否能支持下？

看文档   https://github.com/mei-rune/GoBatis/blob/master/docs/enhance.md

**Comment by mei-rune** [comment]
做不到， jdbc 的驱动有  Offset() 和 Limit(),   go 的驱动没有

**Comment by Gxiaodiao** [comment]
```
type MultRowResult struct {
	ctx       context.Context // nolint
	o         *connection
	tx        DBRunner
	id        string
	sql       string
	sqlParams []interface{}
	rows      *sql.Rows
	err       error
}
```
sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参

**Comment by Gxiaodiao** [comment]
> 做不到， jdbc 的驱动有 Offset() 和 Limit(), go 的驱动没有
> 
> mysql 的 limit 语句修复了

非常感谢

**Comment by Gxiaodiao** [comment]
> ```
> type MultRowResult struct {
> 	ctx       context.Context // nolint
> 	o         *connection
> 	tx        DBRunner
> 	id        string
> 	sql       string
> 	sqlParams []interface{}
> 	rows      *sql.Rows
> 	err       error
> }
> ```
> 
> sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参

分页 我的想法是，从MultRowResult里面获取sql，然后 在最后 拼接 limit 分页参数，求总数，在sql的基础的上，包装下 select
count(0) from (sql)t 这样
可以在写两个方法，一个求参数的接口，一个增加分页参数的接口
你看看，我这个思路是否可以，如果在xml里面 写，xml 很多重复的，也不够灵活

**Comment by mei-rune** [comment]
> ```
> type MultRowResult struct {
> 	ctx       context.Context // nolint
> 	o         *connection
> 	tx        DBRunner
> 	id        string
> 	sql       string
> 	sqlParams []interface{}
> 	rows      *sql.Rows
> 	err       error
> }
> ```
> 
> sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参

有一个  SQL() 方法

**Comment by Gxiaodiao** [comment]
> > ```
> > type MultRowResult struct {
> > 	ctx       context.Context // nolint
> > 	o         *connection
> > 	tx        DBRunner
> > 	id        string
> > 	sql       string
> > 	sqlParams []interface{}
> > 	rows      *sql.Rows
> > 	err       error
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参
> 
> 有一个 SQL() 方法

只是获取到参数值，修改后，不能赋值

**Comment by mei-rune** [comment]
> > ```
> > type MultRowResult struct {
> > 	ctx       context.Context // nolint
> > 	o         *connection
> > 	tx        DBRunner
> > 	id        string
> > 	sql       string
> > 	sqlParams []interface{}
> > 	rows      *sql.Rows
> > 	err       error
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参
> 
> 分页 我的想法是，从MultRowResult里面获取sql，然后 在最后 拼接 limit 分页参数，求总数，在sql的基础的上，包装下 select count(0) from (sql)t 这样 可以在写两个方法，一个求参数的接口，一个增加分页参数的接口 你看看，我这个思路是否可以，如果在xml里面 写，xml 很多重复的，也不够灵活

这个用法本来就是和我的理念是冲突的
你完全没有必要用 MultRowResult ， 你直接定义一个这样子的方法就行了


SelectAll( paramsxxxxxxxxxx , page int, size int) ([]map[string]interface{}, error)

你调用  SelectAll(xxxx,  2, 10) 后， 对  map[string]interface{} 做处理就行了。


另外有周未有空时解决一下 map[string]interface{} 中 float 的问题， 你连额外处理都不用了。

**Comment by mei-rune** [comment]
另外你对分页有执念的话， 你可以在用 SQL() 方法获得  sql 和args 后， args 是参数数组，你可以直接这个数组中的 offset 和 limit  这两个参数

**Comment by Gxiaodiao** [comment]
> > > ```
> > > type MultRowResult struct {
> > > 	ctx       context.Context // nolint
> > > 	o         *connection
> > > 	tx        DBRunner
> > > 	id        string
> > > 	sql       string
> > > 	sqlParams []interface{}
> > > 	rows      *sql.Rows
> > > 	err       error
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参
> > 
> > 
> > 分页 我的想法是，从MultRowResult里面获取sql，然后 在最后 拼接 limit 分页参数，求总数，在sql的基础的上，包装下 select count(0) from (sql)t 这样 可以在写两个方法，一个求参数的接口，一个增加分页参数的接口 你看看，我这个思路是否可以，如果在xml里面 写，xml 很多重复的，也不够灵活
> 
> 这个用法本来就是和我的理念是冲突的 你完全没有必要用 MultRowResult ， 你直接定义一个下面这样子的方法就行了
> 
> SelectAll( paramsxxxxxxxxxx , page int, size int) ([]map[string]interface{}, error)
> 
> 你调用 SelectAll(xxxx, 2, 10) 后， 对 map[string]interface{} 做处理就行了。
> 
> 另外我在周未有空时解决一下 map[string]interface{} 中 float 的问题， 你连额外处理都不用了。

我可能说的可能不是很对啊
"你完全没有必要用 MultRowResult" 这需要的吧，我需要你的接口 去解析xml，才能获取到sql，参数，
SelectAll( paramsxxxxxxxxxx , page int, size int) ([]map[string]interface{}, error) 这个定义了，怎么使用，麻烦指点下

**Comment by mei-rune** [comment]
这里有例子
https://github.com/mei-rune/GoBatis/blob/c88deb2a277350364cfa7f8056d0eeb63d04ce44/example/users_with_autogensql.go#L17

这里有调用
https://github.com/mei-rune/GoBatis/blob/c88deb2a277350364cfa7f8056d0eeb63d04ce44/example/users_test.go#L207

**Comment by mei-rune** [comment]
> > > ```
> > > type MultRowResult struct {
> > > 	ctx       context.Context // nolint
> > > 	o         *connection
> > > 	tx        DBRunner
> > > 	id        string
> > > 	sql       string
> > > 	sqlParams []interface{}
> > > 	rows      *sql.Rows
> > > 	err       error
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > sql 这个参数，是否能变成public，这样 我可以拿到这个sql，拼接下分页参数，就不需要在xml进行传参
> > 
> > 
> > 分页 我的想法是，从MultRowResult里面获取sql，然后 在最后 拼接 limit 分页参数，求总数，在sql的基础的上，包装下 select count(0) from (sql)t 这样 可以在写两个方法，一个求参数的接口，一个增加分页参数的接口 你看看，我这个思路是否可以，如果在xml里面 写，xml 很多重复的，也不够灵活
> 
> 这个用法本来就是和我的理念是冲突的 你完全没有必要用 MultRowResult ， 你直接定义一个下面这样子的方法就行了
> 
> SelectAll( paramsxxxxxxxxxx , page int, size int) ([]map[string]interface{}, error)
> 
> 你调用 SelectAll(xxxx, 2, 10) 后， 对 map[string]interface{} 做处理就行了。
> 
> 另外我在周未有空时解决一下 map[string]interface{} 中 float 的问题， 你连额外处理都不用了。

map[string]interface{} 中 float 的问题,  我修好了
