### ISSUE TITLE
在foreach标签里，做判断的时候，bool类型的字段会变为nil

### ISSUE THREAD

**Issue by Gxiaodiao** [mei-rune/GoBatis#16]
```
 <foreach collection="CategoryList" item="category" index="index">
                        <if test="OperatorBusinessProfit">
                            sum(case when t.data_mark = 'A' then category_#{category}_operator_cost else 0 end) as category_#{category}_operator_cost,
                            sum(case when t.data_mark = 'A' then category_#{category}_agency_point else 0 end) as category_#{category}_agency_point,
                            sum(case when t.data_mark = 'A' then category_#{category}_estimate_commission else 0 end) as category_#{category}_estimate_commission,
                        </if>
                        sum(case when t.data_mark = 'A' then category_#{category}_estimate_capacity else 0 end) as category_#{category}_estimate_capacity,
                        sum(case when t.data_mark = 'A' then category_#{category}_commission else 0 end) as category_#{category}_commission,
                        sum(case when t.data_mark = 'A' then category_#{category}_counts else 0 end) as category_#{category}_counts,
                        sum(case when t.data_mark = 'A' then category_#{category}_price else 0 end) as category_#{category}_price,
                    </foreach>
```
在foreach标签里，OperatorBusinessProfit是bool类型的，在使用的时候
```
<if test="OperatorBusinessProfit">
````
提示： err:"execute `OperatorBusinessProfit` fail, result of test expression is nil - OperatorBusinessProfit"
麻烦看看

**Comment by mei-rune** [comment]
这个好像是的， 当初我故意做的， 我一会改一下， 不过你这个 sql 有问题
 sum(case when t.data_mark = 'A' then category_#{category}_operator_cost else 0 end) as category_#{category}_operator_cost,
 
 改成
 
  sum(case when t.data_mark = 'A' then  category_<print value="category />_operator_cost else 0 end) as category_<print value="category />_operator_cost,

**Comment by mei-rune** [comment]
已提交

**Comment by mei-rune** [comment]
> ```
>  <foreach collection="CategoryList" item="category" index="index">
>                         <if test="OperatorBusinessProfit">
>                             sum(case when t.data_mark = 'A' then category_#{category}_operator_cost else 0 end) as category_#{category}_operator_cost,
>                             sum(case when t.data_mark = 'A' then category_#{category}_agency_point else 0 end) as category_#{category}_agency_point,
>                             sum(case when t.data_mark = 'A' then category_#{category}_estimate_commission else 0 end) as category_#{category}_estimate_commission,
>                         </if>
>                         sum(case when t.data_mark = 'A' then category_#{category}_estimate_capacity else 0 end) as category_#{category}_estimate_capacity,
>                         sum(case when t.data_mark = 'A' then category_#{category}_commission else 0 end) as category_#{category}_commission,
>                         sum(case when t.data_mark = 'A' then category_#{category}_counts else 0 end) as category_#{category}_counts,
>                         sum(case when t.data_mark = 'A' then category_#{category}_price else 0 end) as category_#{category}_price,
>                     </foreach>
> ```
> 
> 在foreach标签里，OperatorBusinessProfit是bool类型的，在使用的时候
> 
> ```
> <if test="OperatorBusinessProfit">
> ```
> 
> 提示： err:"execute `OperatorBusinessProfit` fail, result of test expression is nil - OperatorBusinessProfit" 麻烦看看

这个改成

 ```
                        <if test="OperatorBusinessProfit">
                          <foreach collection="CategoryList" item="category" index="index">
                            sum(case when t.data_mark = 'A' then category_#{category}_operator_cost else 0 end) as category_#{category}_operator_cost,
                            sum(case when t.data_mark = 'A' then category_#{category}_agency_point else 0 end) as category_#{category}_agency_point,
                            sum(case when t.data_mark = 'A' then category_#{category}_estimate_commission else 0 end) as category_#{category}_estimate_commission, 
                          </foreach>
                        </if>
                       <foreach collection="CategoryList" item="category" index="index">
                        sum(case when t.data_mark = 'A' then category_#{category}_estimate_capacity else 0 end) as category_#{category}_estimate_capacity,
                        sum(case when t.data_mark = 'A' then category_#{category}_commission else 0 end) as category_#{category}_commission,
                        sum(case when t.data_mark = 'A' then category_#{category}_counts else 0 end) as category_#{category}_counts,
                        sum(case when t.data_mark = 'A' then category_#{category}_price else 0 end) as category_#{category}_price,
                       </foreach>
 ```

**Comment by Gxiaodiao** [comment]
非常感谢
