### ISSUE TITLE
我也开发了一个模板处理sql的工具

### ISSUE THREAD

**Issue by tianxinzizhen** [mei-rune/GoBatis#7]
我看了作者的文档，跟我想的比较类似，我虽然借鉴了mybaties理念, 但是作者还是更接近mybaties，作者的一些功能正是我要开发的，我的没有那么复杂，很佩服作者对mybaties研究那么深入

**Comment by mei-rune** [comment]
我对 mybaties 没有什么研究， 只是会使用
