### ISSUE TITLE
xml 文件的语法格式 能给一个demo吗

### ISSUE THREAD

**Issue by Gxiaodiao** [mei-rune/GoBatis#8]
xml文件的语法格式给你一个demo吗，比如 if forech when 这种的例子，谢谢

**Comment by mei-rune** [comment]
if foreach when 都是从 mybatis 中抄过来的， 和 mybatis 基本上一致， 我加了例子， 但还没有添加测试
请见 example_xml/xmlfiles/postgres/test.xml  中 Users.SelectAll 方法， 更多例子请见
core\xml_test.go

**Comment by Gxiaodiao** [comment]
你好，方便加个微信吗

**Comment by Gxiaodiao** [comment]
我的mapper文件
`<select id="test" >
        select
        <if test="param.groupByFieldNames != null and param.groupByFieldNames != ''">
            ${param.groupByFieldNames},
        </if>
        <choose>
            <when test="param.categoryList == null or param.categoryList.size() == 0">
                <if test="param.lookOperatorBusinessProfit">
                    SUM(IFNULL(t1.operator_cost, 0)) as operatorCost,
                    SUM(t1.estimate_commission) as estimateCommission,
                    SUM(t1.agency_point) as agencyPoint,
                    SUM(t1.practical_commission) as practicalCommission,
                    SUM(t1.settlement_price) as settlementPrice,
                    SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0)) - IFNULL(t1.operator_cost, 0)) as grossMargin,
                </if>
                SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0))) AS price,
                SUM(IF(t1.business_status = 2, -1, 1)) as busCount,
                SUM(t1.estimate_capacity) as estimateCapacity,
                SUM(t1.deduction_price) as deductionPrice,
                SUM(t1.commission) as commission
            </when>
            <otherwise>
                <if test="param.lookOperatorBusinessProfit">
                    SUM(IFNULL(t1.operator_cost, 0)) as category_0_operator_cost,
                    SUM(t1.agency_point) as category_0_agency_point,
                    SUM(t1.estimate_commission) as category_0_estimate_commission,
                </if>
                SUM(t1.estimate_capacity) as category_0_estimate_capacity,
                SUM(t1.commission) as category_0_commission,
                SUM(t1.counts) as category_0_counts,
                SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0))) AS category_0_price,
                <trim suffixOverrides=",">
                    <foreach collection="param.categoryList" item="category" index="index">
                        <if test="param.lookOperatorBusinessProfit">
                            SUM(IF(t1.category_id = ${category}, IFNULL(t1.operator_cost, 0), 0)) as category_${category}_operator_cost,
                            SUM(IF(t1.category_id = ${category}, t1.agency_point, 0)) as category_${category}_agency_point,
                            SUM(IF(t1.category_id = ${category}, t1.estimate_commission, 0)) as category_${category}_estimate_commission,
                        </if>
                        SUM(IF(t1.category_id = ${category}, t1.estimate_capacity, 0)) as category_${category}_estimate_capacity,
                        SUM(IF(t1.category_id = ${category}, t1.commission, 0)) as category_${category}_commission,
                        SUM(IF(t1.category_id = ${category}, t1.counts, 0)) as category_${category}_counts,
                        SUM(IF(t1.category_id = ${category}, IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0)), 0)) as category_${category}_price,
                    </foreach>
                </trim>
            </otherwise>
        </choose>
        from (
        select t1.*,
        t1.c_channel as channel_id,
        DATE_FORMAT(t1.handle_time, '%Y-%m') as month_str,
        CONCAT(IFNULL(t1.product_name, ''),IF(t1.product_color is null, '', CONCAT(' ',t1.product_color))) as product_full_name,
        t2.area,
        t2.depart_name,
        t2.small_area_id,
        t2.small_area_name,
        t2.big_area_id,
        t2.big_area_name
        from (select * from dwd_operator_services_neo where tenant_id = #{tenantId}) t1
        left join dim_dept_info_neo t2 on t1.tenant_id = t2.tenant_id and t1.area_id = t2.id
        <where>
            <include refid="searchWhereNoPageNew" />
        </where>
        ) t1
        <if test="param.groupByFieldNames != null and param.groupByFieldNames != ''">
            group by ${param.groupByFieldNames}
        </if>
        <if test="param.categoryList == null or param.categoryList.size() == 0">
            <choose>
                <when test="param.sortType != null and param.sortRule != null and (param.sortRule == 1 or param.sortRule == 2)">
                    <choose>
                        <when test="param.sortType == 4">
                            <if test="param.sortRule == 1">
                                order by busCount desc, ${param.orderByFieldNames}
                            </if>
                            <if test="param.sortRule == 2">
                                order by busCount, ${param.orderByFieldNames}
                            </if>
                        </when>
                        <when test="param.sortType == 5 and param.lookOperatorBusinessProfit">
                            <if test="param.sortRule == 1">
                                order by operatorCost desc, ${param.orderByFieldNames}
                            </if>
                            <if test="param.sortRule == 2">
                                order by operatorCost, ${param.orderByFieldNames}
                            </if>
                        </when>
                        <when test="param.sortType == 6 and param.lookOperatorBusinessProfit">
                            <if test="param.sortRule == 1">
                                order by grossMargin desc, ${param.orderByFieldNames}
                            </if>
                            <if test="param.sortRule == 2">
                                order by grossMargin, ${param.orderByFieldNames}
                            </if>
                        </when>
                        <when test="param.sortType == 7 and param.lookOperatorBusinessProfit">
                            <if test="param.sortRule == 1">
                                order by practicalCommission desc, ${param.orderByFieldNames}
                            </if>
                            <if test="param.sortRule == 2">
                                order by practicalCommission, ${param.orderByFieldNames}
                            </if>
                        </when>
                        <otherwise>
                            order by busCount desc, ${param.orderByFieldNames}
                        </otherwise>
                    </choose>
                </when>
                <otherwise>
                    order by busCount desc, ${param.orderByFieldNames}
                </otherwise>
            </choose>
        </if>
    </select>`
报错信息：
Error parse file 'user.xml' on 'test': sql is invalid dynamic sql of 'test', expression 'param.groupByFieldNames != null and param.groupByFieldNames != ''' is invalid: Unable to access unexported field 'groupByFieldNames' in token 'param.groupByFieldNames'

**Comment by Gxiaodiao** [comment]
有个问题 if里面有个条件判断 and or 这种怎么写，直接and就报错
Error parse file 'user.xml' on 'Users.countUsers': sql is invalid dynamic sql of 'Users.countUsers', expression 'Area==8 and isNotEmpty(Name)' is invalid: Cannot transition token types from NUMERIC [8] to VARIABLE [and]
        
        select count(0) from user

        <where>
         <if test="Area==8 and isNotEmpty(Name)">
             and area = #{Area}
         </if>


        </where>

**Comment by mei-rune** [comment]
> 有个问题 if里面有个条件判断 and or 这种怎么写，直接and就报错 Error parse file 'user.xml' on 'Users.countUsers': sql is invalid dynamic sql of 'Users.countUsers', expression 'Area==8 and isNotEmpty(Name)' is invalid: Cannot transition token types from NUMERIC [8] to VARIABLE [and]
> 
> ```
>     select count(0) from user
> 
>     <where>
>      <if test="Area==8 and isNotEmpty(Name)">
>          and area = #{Area}
>      </if>
> 
> 
>     </where>
> ```

我用的是 github.com/Knetic/govaluate 这个库， 它不支持 and 和 or 这两个逻辑操作符， 它是用 && 和 ||, 但这两个在 xml 中需要转义， 写起来太麻烦了， 现在我添加了  or 和 and 的支持了， 你用最新版本测试就好了

另外 小于号 <  也有同样的问题， 我没有更好的方法， 你可以 &lt;  替换它

**Comment by mei-rune** [comment]
> 我的mapper文件 `<select id="test" > select <if test="param.groupByFieldNames != null and param.groupByFieldNames != ''"> ${param.groupByFieldNames}, </if> <choose> <when test="param.categoryList == null or param.categoryList.size() == 0"> <if test="param.lookOperatorBusinessProfit"> SUM(IFNULL(t1.operator_cost, 0)) as operatorCost, SUM(t1.estimate_commission) as estimateCommission, SUM(t1.agency_point) as agencyPoint, SUM(t1.practical_commission) as practicalCommission, SUM(t1.settlement_price) as settlementPrice, SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0)) - IFNULL(t1.operator_cost, 0)) as grossMargin, </if> SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0))) AS price, SUM(IF(t1.business_status = 2, -1, 1)) as busCount, SUM(t1.estimate_capacity) as estimateCapacity, SUM(t1.deduction_price) as deductionPrice, SUM(t1.commission) as commission </when> <otherwise> <if test="param.lookOperatorBusinessProfit"> SUM(IFNULL(t1.operator_cost, 0)) as category_0_operator_cost, SUM(t1.agency_point) as category_0_agency_point, SUM(t1.estimate_commission) as category_0_estimate_commission, </if> SUM(t1.estimate_capacity) as category_0_estimate_capacity, SUM(t1.commission) as category_0_commission, SUM(t1.counts) as category_0_counts, SUM(IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0))) AS category_0_price, <trim suffixOverrides=","> <foreach collection="param.categoryList" item="category" index="index"> <if test="param.lookOperatorBusinessProfit"> SUM(IF(t1.category_id = ${category}, IFNULL(t1.operator_cost, 0), 0)) as category_${category}_operator_cost, SUM(IF(t1.category_id = ${category}, t1.agency_point, 0)) as category_${category}_agency_point, SUM(IF(t1.category_id = ${category}, t1.estimate_commission, 0)) as category_${category}_estimate_commission, </if> SUM(IF(t1.category_id = ${category}, t1.estimate_capacity, 0)) as category_${category}_estimate_capacity, SUM(IF(t1.category_id = ${category}, t1.commission, 0)) as category_${category}_commission, SUM(IF(t1.category_id = ${category}, t1.counts, 0)) as category_${category}_counts, SUM(IF(t1.category_id = ${category}, IF(t1.business_status = 2, IF(t1.return_price is not null, (0 - t1.return_price), (0 - IFNULL(t1.price,0))), IFNULL(t1.price,0)), 0)) as category_${category}_price, </foreach> </trim> </otherwise> </choose> from ( select t1.*, t1.c_channel as channel_id, DATE_FORMAT(t1.handle_time, '%Y-%m') as month_str, CONCAT(IFNULL(t1.product_name, ''),IF(t1.product_color is null, '', CONCAT(' ',t1.product_color))) as product_full_name, t2.area, t2.depart_name, t2.small_area_id, t2.small_area_name, t2.big_area_id, t2.big_area_name from (select * from dwd_operator_services_neo where tenant_id = #{tenantId}) t1 left join dim_dept_info_neo t2 on t1.tenant_id = t2.tenant_id and t1.area_id = t2.id <where> <include refid="searchWhereNoPageNew" /> </where> ) t1 <if test="param.groupByFieldNames != null and param.groupByFieldNames != ''"> group by ${param.groupByFieldNames} </if> <if test="param.categoryList == null or param.categoryList.size() == 0"> <choose> <when test="param.sortType != null and param.sortRule != null and (param.sortRule == 1 or param.sortRule == 2)"> <choose> <when test="param.sortType == 4"> <if test="param.sortRule == 1"> order by busCount desc, ${param.orderByFieldNames} </if> <if test="param.sortRule == 2"> order by busCount, ${param.orderByFieldNames} </if> </when> <when test="param.sortType == 5 and param.lookOperatorBusinessProfit"> <if test="param.sortRule == 1"> order by operatorCost desc, ${param.orderByFieldNames} </if> <if test="param.sortRule == 2"> order by operatorCost, ${param.orderByFieldNames} </if> </when> <when test="param.sortType == 6 and param.lookOperatorBusinessProfit"> <if test="param.sortRule == 1"> order by grossMargin desc, ${param.orderByFieldNames} </if> <if test="param.sortRule == 2"> order by grossMargin, ${param.orderByFieldNames} </if> </when> <when test="param.sortType == 7 and param.lookOperatorBusinessProfit"> <if test="param.sortRule == 1"> order by practicalCommission desc, ${param.orderByFieldNames} </if> <if test="param.sortRule == 2"> order by practicalCommission, ${param.orderByFieldNames} </if> </when> <otherwise> order by busCount desc, ${param.orderByFieldNames} </otherwise> </choose> </when> <otherwise> order by busCount desc, ${param.orderByFieldNames} </otherwise> </choose> </if> </select>` 报错信息： Error parse file 'user.xml' on 'test': sql is invalid dynamic sql of 'test', expression 'param.groupByFieldNames != null and param.groupByFieldNames != ''' is invalid: Unable to access unexported field 'groupByFieldNames' in token 'param.groupByFieldNames'

这个是你对  golang 不熟吧， golang 没有 public 和 private 关键字， 它是用首字母大小写来限制其它包能不能访问字段和函数的

**Comment by mei-rune** [comment]
> 你好，方便加个微信吗

还是不了， 我很忙， 没有时间和别人聊， 有问题提BUG， 我尽快回。

这个是我们自用的库， 有人用我高兴， 没人用我也无所谓，我不会花时间在社区推广的。

**Comment by Gxiaodiao** [comment]
<trim suffixOverrides=","> 这个标签 支持吗 我测试了下 貌似不支持

**Comment by Gxiaodiao** [comment]
<trim suffixOverrides=","> 这个标签可以支持下嘛 貌似现在不支持的样子

**Comment by Gxiaodiao** [comment]
> > 你好，方便加个微信吗
> 
> 还是不了， 我很忙， 没有时间和别人聊， 有问题提BUG， 我尽快回。
> 
> 这个是我们自用的库， 有人用我高兴， 没人用我也无所谓，我不会花时间在社区推广的。

好的 谢谢

**Comment by mei-rune** [comment]
> > 有个问题 if里面有个条件判断 and or 这种怎么写，直接and就报错 Error parse file 'user.xml' on 'Users.countUsers': sql is invalid dynamic sql of 'Users.countUsers', expression 'Area==8 and isNotEmpty(Name)' is invalid: Cannot transition token types from NUMERIC [8] to VARIABLE [and]
> > ```
> >     select count(0) from user
> > 
> >     <where>
> >      <if test="Area==8 and isNotEmpty(Name)">
> >          and area = #{Area}
> >      </if>
> > 
> > 
> >     </where>
> > ```
> 
> 我用的是 github.com/Knetic/govaluate 这个库， 它不支持 and 和 or 这两个逻辑操作符， 它是用 && 和 ||, 但这两个在 xml 中需要转义， 写起来太麻烦了， 现在我添加了 or 和 and 的支持了， 你用最新版本测试就好了
> 
> 另外 小于号 < 也有同样的问题， 我没有更好的方法， 你可以 &lt; 替换它

刚才我也像 mybatis 一样用 gt, gte，lt 和 lte 代替  >,>=, < 和 <=

**Comment by Gxiaodiao** [comment]
> > 这个标签可以支持下嘛 貌似现在不支持的样子
> 
> 哪个标签？

`<trim>`这个标签，去掉前后指定的字符串

**Comment by mei-rune** [comment]
> > > 这个标签可以支持下嘛 貌似现在不支持的样子
> > 
> > 
> > 哪个标签？
> 
> `<trim>`这个标签，去掉前后指定的字符串

我实现了， 和 mybatis 是一样的， 你可以试一下

**Comment by Gxiaodiao** [comment]
> > > > 这个标签可以支持下嘛 貌似现在不支持的样子
> > > 
> > > 
> > > 哪个标签？
> > 
> > 
> > `<trim>`这个标签，去掉前后指定的字符串
> 
> 我实现了， 和 mybatis 是一样的， 你可以试一下

我试了试 没报错，但是生效，麻烦看下，
![image](https://github.com/mei-rune/GoBatis/assets/10322122/970546e1-8c4c-4a80-bec2-46504114cf9d)

`<trim suffixOverrides=",">
            id,name,age,address,area,card_no,
        </trim>`

**Comment by mei-rune** [comment]
已经修好了

**Comment by Gxiaodiao** [comment]
> 已经修好了

非常感谢，测试过了 没有问题了，点赞

**Comment by Gxiaodiao** [comment]
再提一个问题，可以支持<incloud>这个标签吗

**Comment by mei-rune** [comment]
> 再提一个问题，可以支持这个标签吗

哪个？

**Comment by Gxiaodiao** [comment]
> > 再提一个问题，可以支持这个标签吗
> 
> 哪个？

`<incloud>`这个标签的支持

**Comment by mei-rune** [comment]
已支持

**Comment by mei-rune** [comment]
resultMap 我不会支持的， 另外 ${} 我有 <print /> 替代

**Comment by Gxiaodiao** [comment]
> resultMap 我不会支持的， 另外 ${} 我有 替代

好的 非常感谢 resultMap 在golang 感觉不需要吧

**Comment by mei-rune** [comment]
> > resultMap 我不会支持的， 另外 ${} 我有 替代
> 
> 好的 非常感谢 resultMap 在golang 感觉不需要吧

是的， 没有什么用， 在结构的 tag 中已经有字段的映射了，这里在加 resultMap 就多余了， resultMap 的其它功能，我这边又没有实现， 所以暂时不添加它的支持了。

**Comment by mei-rune** [comment]
我先关了， 有问题再提BUG吧
